### ISSUE TITLE
Sprint v0.4

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#151]
## Sprint v0.4
**Administrativo**

 - [ ] EPIC: Usuario administrativo navega el sistema #52

**Recupero**
 - [ ] Permitir editar la cantidad de atenciones según código del nomenclador #39
 - [ ] Denuncia de Internacion #35

**Otros**
 - [ ] Definir permisos para vistas #123
 - [ ] Revisar la grabacion de medidas anexas #120
 - [ ] Permitir definir permisos de usuarios #98
 - [ ] Revisar las [notas de las últimas reuniones](https://docs.google.com/document/d/1JhNzY28MxRQ1S75B8wWIeQsak9yAE_vWtkQvsQec11M/edit) y pasarlas a tickets.
 
 Versión 0.4
  - [ ] Agregar datos al turno imprimible #130
  - [ ] Mejoras comprobante impreso de turno #131
  - [ ] Imágenes y laboratorio #108
  - [ ] Turnos: copiar de semana anterior #93
  - [ ] Agregar, editar y mostrar modelos #79 (widget mapa centros de salud)
