### ISSUE TITLE
Asignar permiso gestionar turno GRUPO_ADMIN

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#174]
Según el manual un usuario administrativo puede gestionar turnos:

-  ~[ ] Asignarle permiso para gestionar turno a GRUPO_ADMIN. [Línea en el repo](https://github.com/cluster311/ggg/blob/e9f853f8134df65e6addaae634970347ab8a7857/core/base_permission.py#L26)~
-  Ver porque está comentada la creación del permiso gestionar turno

**Comment by marcorichetta** [comment]
Me puse a entender que hace realmente la vista `/gestionar_turnos` y no es tan simple como para eliminarla porque tiene algunas cosas interesantes.

@avdata99 Estaría bueno saber para qué surge `/gestionar_turnos`, ya que fue hecha **después** de `/agendar`, y no esta "abandonada" como pensé en algún momento.

# Agendar

**URL:** `agendar/`

**VIEW:** `agendar`

**TEMPLATE:** `calendario-agregar.html`

**FUNCIONES JS:**

- `ConfirmTurn()` →
- Hace PUT en `calendario.confirm` →
- Lleva a la view `confirm_turn`

### Paciente no existe

- Mensaje de error → "Historia clinica no inicializada"

### Modal con turnos agendados

- Te muestra el modal con los datos del turno y el paciente
- Te da la opción de imprimir

# Gestionar

**URL:** `gestionar_turnos/`

**VIEW:** `gestion_turnos`

**TEMPLATE:** `calendario-gestionar.html`

**FUNCIONES JS:**

- `ConfirmTurn()` →
- Hace PUT en `calendario.gestion_turno` →
- Lleva a la view `gestion_turno` (sin S)

### Paciente no existe

- En la misma página aparece un nuevo modal que permite dar de alta al paciente

### Crear Sobreturno

- Está permitido solo con el permiso `calendario.can_gestionar_turnos`
- ESTE PERMISO ESTA COMENTADO EN EL COMANDO QUE ASIGNA LOS PERMISOS INICIALES DEL SISTEMA, ES DECIR EL PERMISO NO SE LE ASIGNA A NINGÚN GRUPO.

# To-do

- [ ]  Ver porque se comentó la creación del permiso `gestionar_turno`.
- [ ]  Ver qué funciones de Javascript pueden ser útiles.

**Comment by avdata99** [comment]
- [ ] Elegir una de las dos y eliminar la otra
 - [ ] Pasarle todo lo mejor a la que quede
 - [ ] Revisar los permisos, eliminar los que no existen mas
 - [ ] Revisar los tests
