### ISSUE TITLE
EPIC: Usuario administrativo navega el sistema

### ISSUE THREAD

**Issue by avdata99** [cluster311/ggg#52]
**Hacer una revisión general y definir issues nuevos.**

Tareas a chequear para considerar que tenemos una versión 0.1.
No todos tienen tickets, los que no lo tengan y lo ameriten deberán tenerlo.
El manual de usuario debería alimentar a este ticket con las historias de usuario y otros requerimientos

 - [x] El usuario administrativo del municipio tiene una URL donde iniciar en un sitio identificado con un nombre/logo preferentemente diferente al admin de django o al menos una version diferenciada
 - [x] Un administrador con permiso especiales crea un usuario
 - [ ] Un usuario olvida su contraseña y debe recuperarla. Revisar que el proceso funcione de django funcione.
 - [ ] Home administrativa. El usuario se logue: ¿que ve? Definir esa home. ¿Vamos al admin nuevo con los menues?
 - [ ] Un usuario debe crear los turnos de una semana para un centro de salud
   - [x] ¿Puede elegir fechas, especialidad y profesional de maneara simple y clara?
   - [ ] ¿Los demás administradores pueden mirar un calendario con todas estos turnos programados?
   - [ ] ¿Si se superponen turnos de un mismo profesiona surge una alerta?
 - [ ] Un paciente llega a su turno programado ¿Que pantalla mira el usuario del sistema que lo recibe?
   - [ ] ¿Puede el usuario marcar el turno como iniciado?
   - [ ] ¿Cuando se atiende el médico tiene una interface donde cargar el diagnóstico?
   - [ ] ¿El médico puede derivar sacando un nuevo turno con el nuevo _servicio_?
   - [ ] ¿El médico y el administrativo ven diferntes campos de modo de que de manera segura cada uno cargue su parte?
   - [ ] ¿Si el usuario tiene una obra social el sistema muestra cual es?
   - [ ] ¿Se puede imprimir el Anexo II de recupero para que paciente, médico y administrativo firmen?
   - [ ] ¿En caso de que firmen el administrativo puede scanear/fotografiar el documento y guardarlo en el sistema para la futura facturación?

Usuario ciudadano
 - [ ] ¿El ciudadano tiene una URL donde generar su usuario o loguarse? 
 - [ ] ¿Estamos conectados al API de vecino virtual de la muni?
 - [ ] ¿El ciudadano cuando se conecta tiene una hoem con info a cerca de sus turnos y otras novedades del municipio?
 - [ ] ¿El ciudadano puede sacar un turno de manera fácil?
 - [ ] ¿El usuario puede recibir notificaciones sobre sus próximos turnos?
 - [ ] ¿El usuario puede cancelar un turno?

**Comment by ryacyna** [comment]
- Es posible crear un nuevo turno *SIN ESPECIFICAR el PACIENTE*
- No se puede *AGREGAR "Direccion"* en carpeta familiar,  por lo que :
                 -  No se puede *CREAR Carpeta familiar*, por lo que:
                            - No se pueden *CREAR* pacientes.
- En *Añadir address*  tiene todos los captions en ingles.

**Comment by ryacyna** [comment]
Al loguearse NO HAY opcion   *"Olvide mi contraseña"*

**Comment by ryacyna** [comment]
Existe el TURNERO tipo CALENDARIO ?  cual es el link ?
